### ISSUE TITLE
clean up

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/content-marketing#1]
let's move articles content away from that repository

- https://github.com/LLazyEmail/awesome-email-marketing/tree/main/Files%20for%20articles

- https://github.com/LLazyEmail/awesome-email-marketing/blob/main/our-content.md

**Comment by Svitlana007** [comment]
where?

**Comment by atherdon** [comment]
sorry - I decided to migrate everything that isn't necessary to "awesome-list" away.
please move it into https://github.com/LLazyEmail/content-marketing repository

**Comment by Svitlana007** [comment]
[Create our-content.md #7](https://github.com/LLazyEmail/content-marketing/pull/7)
[Delete our-content.md #176](https://github.com/LLazyEmail/awesome-email-marketing/pull/176)

**Comment by Svitlana007** [comment]
[Create Best Email Marketing Tools for 2022.md #8](https://github.com/LLazyEmail/content-marketing/pull/8)
[Delete Best Email Marketing Tools for 2022.md #177](https://github.com/LLazyEmail/awesome-email-marketing/pull/177)

[Create Demand Curve: Tested tactics for growing newsletters.md #9](https://github.com/LLazyEmail/content-marketing/pull/9)
[Delete Demand Curve: Tested tactics for growing newsletters.md #178](https://github.com/LLazyEmail/awesome-email-marketing/pull/178)

[Create Email Marketing For eCommerce.md #10](https://github.com/LLazyEmail/content-marketing/pull/10)
[Delete Email Marketing For eCommerce.md #179](https://github.com/LLazyEmail/awesome-email-marketing/pull/179)

[Create Frontend Development.md #11](https://github.com/LLazyEmail/content-marketing/pull/11)
[Delete Frontend Development.md #180](https://github.com/LLazyEmail/awesome-email-marketing/pull/180)

[Create Github.md #12](https://github.com/LLazyEmail/content-marketing/pull/12)
[Delete Github.md #181](https://github.com/LLazyEmail/awesome-email-marketing/pull/181)

[Create Transactional Emails.md #13](https://github.com/LLazyEmail/content-marketing/pull/13)
[Delete Transactional Emails.md #182](https://github.com/LLazyEmail/awesome-email-marketing/pull/182)

[Create newsletters db #95 (27.07.2022).md #14](https://github.com/LLazyEmail/content-marketing/pull/14)
[Delete newsletters db #95 (27.07.2022).md #183](https://github.com/LLazyEmail/awesome-email-marketing/pull/183)

[Create newsletters db #95.md #15](https://github.com/LLazyEmail/content-marketing/pull/15)
[Delete newsletters db #95.md #184](https://github.com/LLazyEmail/awesome-email-marketing/pull/184)

**Comment by Svitlana007** [comment]
Done

**Comment by atherdon** [comment]
wow wow wow - awesome!
